/**
 * This class is generated by jOOQ
 */
package org.sao.aoa.migrator.model.tables;

import org.jooq.*;
import org.jooq.impl.TableImpl;
import org.sao.aoa.migrator.model.AnuarioSchema;
import org.sao.aoa.migrator.model.tables.records.AsoCitaClaseEdadSexoRecord;

/**
 * This class is generated by jOOQ.
 *
 * Relación de edad y sexo de las especie por cita
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AsoCitaClaseEdadSexo extends TableImpl<AsoCitaClaseEdadSexoRecord> {

	private static final long serialVersionUID = -575272757;

	/**
	 * The singleton instance of <code>aso_cita_clase_edad_sexo</code>
	 */
	public static final AsoCitaClaseEdadSexo ASO_CITA_CLASE_EDAD_SEXO = new AsoCitaClaseEdadSexo();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AsoCitaClaseEdadSexoRecord> getRecordType() {
		return AsoCitaClaseEdadSexoRecord.class;
	}

	/**
	 * The column <code>aso_cita_clase_edad_sexo.id</code>. Identificador único de la tabla
	 */
	public final TableField<AsoCitaClaseEdadSexoRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "Identificador único de la tabla");

	/**
	 * The column <code>aso_cita_clase_edad_sexo.cita_id</code>. Identificador de la cita
	 */
	public final TableField<AsoCitaClaseEdadSexoRecord, Integer> CITA_ID = createField("cita_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "Identificador de la cita");

	/**
	 * The column <code>aso_cita_clase_edad_sexo.clase_edad_sexo_id</code>. Identificador de la clase-edad-sexo
	 */
	public final TableField<AsoCitaClaseEdadSexoRecord, Integer> CLASE_EDAD_SEXO_ID = createField("clase_edad_sexo_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "Identificador de la clase-edad-sexo");

	/**
	 * The column <code>aso_cita_clase_edad_sexo.cantidad</code>. Cantidad de individuos por clase de edad-sexo
	 */
	public final TableField<AsoCitaClaseEdadSexoRecord, Integer> CANTIDAD = createField("cantidad", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "Cantidad de individuos por clase de edad-sexo");

	/**
	 * Create a <code>aso_cita_clase_edad_sexo</code> table reference
	 */
	public AsoCitaClaseEdadSexo() {
		this(AnuarioSchema.getTablePrefix() + "aso_cita_clase_edad_sexo", null);
	}

	/**
	 * Create an aliased <code>aso_cita_clase_edad_sexo</code> table reference
	 */
	public AsoCitaClaseEdadSexo(String alias) {
		this(alias, AsoCitaClaseEdadSexo.ASO_CITA_CLASE_EDAD_SEXO);
	}

	private AsoCitaClaseEdadSexo(String alias, Table<AsoCitaClaseEdadSexoRecord> aliased) {
		this(alias, aliased, null);
	}

	private AsoCitaClaseEdadSexo(String alias, Table<AsoCitaClaseEdadSexoRecord> aliased, Field<?>[] parameters) {
		super(alias, AnuarioSchema.ANUARIO_SCHEMA, aliased, parameters, "Relación de edad y sexo de las especie por cita");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AsoCitaClaseEdadSexo as(String alias) {
		return new AsoCitaClaseEdadSexo(alias, this);
	}

	/**
	 * Rename this table
	 */
	public AsoCitaClaseEdadSexo rename(String name) {
		return new AsoCitaClaseEdadSexo(name, null);
	}
}
