/**
 * This class is generated by jOOQ
 */
package org.sao.aoa.migrator.model.tables;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.sao.aoa.migrator.model.AnuarioSchema;
import org.sao.aoa.migrator.model.tables.records.CitaRecord;

import java.sql.Timestamp;

/**
 * This class is generated by jOOQ.
 *
 * cita recopiladas
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cita extends TableImpl<CitaRecord> {

	private static final long serialVersionUID = -1590487117;

	/**
	 * The singleton instance of <code>cita</code>
	 */
	public static final Cita CITA = new Cita();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<CitaRecord> getRecordType() {
		return CitaRecord.class;
	}

	/**
	 * The column <code>cita.id</code>. Identificador de la cita
	 */
	public final TableField<CitaRecord, Integer> ID = createField("id", SQLDataType.INTEGER.nullable(false), this, "Identificador de la cita");

    /**
     * The column <code>cita.id98</code>. Identificador de la cita
     */
    public final TableField<CitaRecord, Integer> ID98 = createField("id98", SQLDataType.INTEGER.nullable(true), this, "Identificador de la cita para migraciones");

	/**
	 * The column <code>cita.fechaAlta</code>. Fecha de alta de la cita
	 */
	public final TableField<CitaRecord, Timestamp> FECHAALTA = createField("fechaAlta", SQLDataType.TIMESTAMP.nullable(false), this, "Fecha de alta de la cita");

	/**
	 * The column <code>cita.cantidad</code>. Número de individuos de la especie citada
	 */
	public final TableField<CitaRecord, Integer> CANTIDAD = createField("cantidad", SQLDataType.INTEGER.nullable(false), this, "Número de individuos de la especie citada");

	/**
	 * The column <code>cita.observaciones</code>. Observaciones sobre la cita
	 */
	public final TableField<CitaRecord, String> OBSERVACIONES = createField("observaciones", SQLDataType.CLOB.length(65535), this, "Observaciones sobre la cita");

	/**
	 * The column <code>cita.indSeleccionada</code>. Indica si la cita es seleccionada para el anuario (1) o no (0)
	 */
	public final TableField<CitaRecord, Byte> INDSELECCIONADA = createField("indSeleccionada", SQLDataType.TINYINT, this, "Indica si la cita es seleccionada para el anuario (1) o no (0)");

	/**
	 * The column <code>cita.lugar_id</code>. Identificador del lugar donde se produjo la cita
	 */
	public final TableField<CitaRecord, Integer> LUGAR_ID = createField("lugar_id", SQLDataType.INTEGER.nullable(false), this, "Identificador del lugar donde se produjo la cita");

	/**
	 * The column <code>cita.indRarezaHomologada</code>. Indica si la cita es de una rareza homologada (1) o no (0)
	 */
	public final TableField<CitaRecord, Integer> INDRAREZAHOMOLOGADA = createField("indRarezaHomologada", SQLDataType.INTEGER, this, "Indica si la cita es de una rareza homologada (1) o no (0)");

	/**
	 * The column <code>cita.observador_principal_id</code>.
	 */
	public final TableField<CitaRecord, Integer> OBSERVADOR_PRINCIPAL_ID = createField("observador_principal_id", SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>cita.clase_reproduccion_id</code>.
	 */
	public final TableField<CitaRecord, Integer> CLASE_REPRODUCCION_ID = createField("clase_reproduccion_id", SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>cita.fuente_id</code>.
	 */
	public final TableField<CitaRecord, Integer> FUENTE_ID = createField("fuente_id", SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>cita.indHabitatRaro</code>. Indica si la cita fue en un habitat raro para la especie vista (1) o no (0)
	 */
	public final TableField<CitaRecord, Byte> INDHABITATRARO = createField("indHabitatRaro", SQLDataType.TINYINT, this, "Indica si la cita fue en un habitat raro para la especie vista (1) o no (0)");

	/**
	 * The column <code>cita.indCriaHabitatRaro</code>. Indica si la cita es de una especie criando en un habitat raro (1) o no (0)
	 */
	public final TableField<CitaRecord, Byte> INDCRIAHABITATRARO = createField("indCriaHabitatRaro", SQLDataType.TINYINT, this, "Indica si la cita es de una especie criando en un habitat raro (1) o no (0)");

	/**
	 * The column <code>cita.indHerido</code>. Indica si el individuo/s citado/s estaba/n herido/s (1) o no (0)
	 */
	public final TableField<CitaRecord, Byte> INDHERIDO = createField("indHerido", SQLDataType.TINYINT, this, "Indica si el individuo/s citado/s estaba/n herido/s (1) o no (0)");

	/**
	 * The column <code>cita.indComportamiento</code>. Descripción del comportamiento de la especie
	 */
	public final TableField<CitaRecord, Byte> INDCOMPORTAMIENTO = createField("indComportamiento", SQLDataType.TINYINT, this, "Descripción del comportamiento de la especie");

	/**
	 * The column <code>cita.especie_id</code>. Identificador de la especie
	 */
	public final TableField<CitaRecord, Integer> ESPECIE_ID
			= createField("especie_id", SQLDataType.INTEGER.nullable(false), this, "Identificador de la especie");

	/**
	 * The column <code>cita.criterio_seleccion_cita_id</code>. Criterio utilizado en la selección de la cita
	 */
	public final TableField<CitaRecord, Integer> CRITERIO_SELECCION_CITA_ID = createField("criterio_seleccion_cita_id", SQLDataType.INTEGER.nullable(false), this, "Criterio utilizado en la selección de la cita");

	/**
	 * The column <code>cita.indActivo</code>.
	 */
	public final TableField<CitaRecord, Byte> INDACTIVO
			= createField("indActivo", SQLDataType.TINYINT.defaulted(true), this, "");

	/**
	 * The column <code>cita.importancia_cita_id</code>. Identificador de la importancia de la cita
	 */
	public final TableField<CitaRecord, Integer> IMPORTANCIA_CITA_ID = createField("importancia_cita_id", SQLDataType.INTEGER.nullable(false).defaulted(true), this, "Identificador de la importancia de la cita");

	/**
	 * The column <code>cita.estudio_id</code>.
	 */
	public final TableField<CitaRecord, Integer> ESTUDIO_ID
			= createField("estudio_id", SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>cita.indPrivacidad</code>. Indica si los datos sensibles de la cita de la especie deben ser privados (0) o públicos (1)
	 */
	public final TableField<CitaRecord, Byte> INDPRIVACIDAD = createField("indPrivacidad", SQLDataType.TINYINT.nullable(false).defaulted(true), this, "Indica si los datos sensibles de la cita de la especie deben ser privados (0) o públicos (1)");

	/**
	 * The column <code>cita.indFoto</code>.
	 */
	public final TableField<CitaRecord, Byte> INDFOTO
			= createField("indFoto", SQLDataType.TINYINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>cita.fechaCreacion</code>.
	 */
	public final TableField<CitaRecord, Timestamp> FECHACREACION
			= createField("fechaCreacion", SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * Create a <code>cita</code> table reference
	 */
	public Cita() {
		this(AnuarioSchema.getTablePrefix() + "cita", null);
	}

	/**
	 * Create an aliased <code>cita</code> table reference
	 */
	public Cita(String alias) {
		this(alias, Cita.CITA);
	}

	private Cita(String alias, Table<CitaRecord> aliased) {
		this(alias, aliased, null);
	}

	private Cita(String alias, Table<CitaRecord> aliased, Field<?>[] parameters) {
		super(alias, AnuarioSchema.ANUARIO_SCHEMA, aliased, parameters, "cita recopiladas");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Cita as(String alias) {
		return new Cita(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Cita rename(String name) {
		return new Cita(name, null);
	}
}
