/**
 * This class is generated by jOOQ
 */
package org.sao.aoa.migrator.model;

import org.sao.aoa.migrator.model.tables.AsoCitaClaseEdadSexo;
import org.sao.aoa.migrator.model.tables.AsoCitaObservador;
import org.sao.aoa.migrator.model.tables.Cita;
import org.sao.aoa.migrator.model.tables.CitaHistorico;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in the schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * Relación de edad y sexo de las especie por cita
	 */
	public static final AsoCitaClaseEdadSexo ASO_CITA_CLASE_EDAD_SEXO = AsoCitaClaseEdadSexo.ASO_CITA_CLASE_EDAD_SEXO;

	/**
	 * Asocia cita y observadores
	 */
	public static final AsoCitaObservador ASO_CITA_OBSERVADOR = AsoCitaObservador.ASO_CITA_OBSERVADOR;

	/**
	 * cita recopiladas
	 */
	public static final Cita CITA = Cita.CITA;

	/**
	 * Históricos de cita recopiladas
	 */
	public static final CitaHistorico CITA_HISTORICO = CitaHistorico.CITA_HISTORICO;
}
