/**
 * This class is generated by jOOQ
 */
package org.sao.aoa.migrator.model.tables.records;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.sao.aoa.migrator.model.tables.AsoCitaClaseEdadSexo;

/**
 * This class is generated by jOOQ.
 *
 * Relación de edad y sexo de las especie por cita
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AsoCitaClaseEdadSexoRecord extends UpdatableRecordImpl<AsoCitaClaseEdadSexoRecord> implements Record4<Integer, Integer, Integer, Integer> {

	private static final long serialVersionUID = -227028755;

	/**
	 * Setter for <code>aso_cita_clase_edad_sexo.id</code>. Identificador único de la tabla
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>aso_cita_clase_edad_sexo.id</code>. Identificador único de la tabla
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>aso_cita_clase_edad_sexo.cita_id</code>. Identificador de la cita
	 */
	public void setCitaId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>aso_cita_clase_edad_sexo.cita_id</code>. Identificador de la cita
	 */
	public Integer getCitaId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>aso_cita_clase_edad_sexo.clase_edad_sexo_id</code>. Identificador de la clase-edad-sexo
	 */
	public void setClaseEdadSexoId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>aso_cita_clase_edad_sexo.clase_edad_sexo_id</code>. Identificador de la clase-edad-sexo
	 */
	public Integer getClaseEdadSexoId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>aso_cita_clase_edad_sexo.cantidad</code>. Cantidad de individuos por clase de edad-sexo
	 */
	public void setCantidad(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>aso_cita_clase_edad_sexo.cantidad</code>. Cantidad de individuos por clase de edad-sexo
	 */
	public Integer getCantidad() {
		return (Integer) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, Integer, Integer, Integer> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, Integer, Integer, Integer> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return AsoCitaClaseEdadSexo.ASO_CITA_CLASE_EDAD_SEXO.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return AsoCitaClaseEdadSexo.ASO_CITA_CLASE_EDAD_SEXO.CITA_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return AsoCitaClaseEdadSexo.ASO_CITA_CLASE_EDAD_SEXO.CLASE_EDAD_SEXO_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return AsoCitaClaseEdadSexo.ASO_CITA_CLASE_EDAD_SEXO.CANTIDAD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getCitaId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getClaseEdadSexoId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getCantidad();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AsoCitaClaseEdadSexoRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AsoCitaClaseEdadSexoRecord value2(Integer value) {
		setCitaId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AsoCitaClaseEdadSexoRecord value3(Integer value) {
		setClaseEdadSexoId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AsoCitaClaseEdadSexoRecord value4(Integer value) {
		setCantidad(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AsoCitaClaseEdadSexoRecord values(Integer value1, Integer value2, Integer value3, Integer value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AsoCitaClaseEdadSexoRecord
	 */
	public AsoCitaClaseEdadSexoRecord() {
		super(AsoCitaClaseEdadSexo.ASO_CITA_CLASE_EDAD_SEXO);
	}

	/**
	 * Create a detached, initialised AsoCitaClaseEdadSexoRecord
	 */
	public AsoCitaClaseEdadSexoRecord(Integer id, Integer citaId, Integer claseEdadSexoId, Integer cantidad) {
		super(AsoCitaClaseEdadSexo.ASO_CITA_CLASE_EDAD_SEXO);

		setValue(0, id);
		setValue(1, citaId);
		setValue(2, claseEdadSexoId);
		setValue(3, cantidad);
	}
}
