/**
 * This class is generated by jOOQ
 */
package org.sao.aoa.migrator.model.tables.records;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record22;
import org.jooq.Row22;
import org.jooq.impl.UpdatableRecordImpl;
import org.sao.aoa.migrator.model.tables.Cita;

import java.sql.Timestamp;

/**
 * This class is generated by jOOQ.
 *
 * cita recopiladas
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CitaRecord
		extends UpdatableRecordImpl<CitaRecord> 
		implements Record22<Integer, Timestamp, Integer, String, Byte, Integer, Integer, Integer, Integer, Integer, Byte, Byte, Byte, Byte, Integer, Integer, Byte, Integer, Integer, Byte, Byte, Timestamp> {

	private static final long serialVersionUID = 81638882;

	/**
	 * Setter for <code>cita.id</code>. Identificador de la cita
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>cita.id</code>. Identificador de la cita
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>cita.fechaAlta</code>. Fecha de alta de la cita
	 */
	public void setFechaalta(Timestamp value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>cita.fechaAlta</code>. Fecha de alta de la cita
	 */
	public Timestamp getFechaalta() {
		return (Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>cita.cantidad</code>. Número de individuos de la especie citada
	 */
	public void setCantidad(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>cita.cantidad</code>. Número de individuos de la especie citada
	 */
	public Integer getCantidad() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>cita.observaciones</code>. Observaciones sobre la cita
	 */
	public void setObservaciones(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>cita.observaciones</code>. Observaciones sobre la cita
	 */
	public String getObservaciones() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>cita.indSeleccionada</code>. Indica si la cita es seleccionada para el anuario (1) o no (0)
	 */
	public void setIndseleccionada(Byte value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>cita.indSeleccionada</code>. Indica si la cita es seleccionada para el anuario (1) o no (0)
	 */
	public Byte getIndseleccionada() {
		return (Byte) getValue(4);
	}

	/**
	 * Setter for <code>cita.lugar_id</code>. Identificador del lugar donde se produjo la cita
	 */
	public void setLugarId(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>cita.lugar_id</code>. Identificador del lugar donde se produjo la cita
	 */
	public Integer getLugarId() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>cita.indRarezaHomologada</code>. Indica si la cita es de una rareza homologada (1) o no (0)
	 */
	public void setIndrarezahomologada(Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>cita.indRarezaHomologada</code>. Indica si la cita es de una rareza homologada (1) o no (0)
	 */
	public Integer getIndrarezahomologada() {
		return (Integer) getValue(6);
	}

	/**
	 * Setter for <code>cita.observador_principal_id</code>.
	 */
	public void setObservadorPrincipalId(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>cita.observador_principal_id</code>.
	 */
	public Integer getObservadorPrincipalId() {
		return (Integer) getValue(7);
	}

	/**
	 * Setter for <code>cita.clase_reproduccion_id</code>.
	 */
	public void setClaseReproduccionId(Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>cita.clase_reproduccion_id</code>.
	 */
	public Integer getClaseReproduccionId() {
		return (Integer) getValue(8);
	}

	/**
	 * Setter for <code>cita.fuente_id</code>.
	 */
	public void setFuenteId(Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>cita.fuente_id</code>.
	 */
	public Integer getFuenteId() {
		return (Integer) getValue(9);
	}

	/**
	 * Setter for <code>cita.indHabitatRaro</code>. Indica si la cita fue en un habitat raro para la especie vista (1) o no (0)
	 */
	public void setIndhabitatraro(Byte value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>cita.indHabitatRaro</code>. Indica si la cita fue en un habitat raro para la especie vista (1) o no (0)
	 */
	public Byte getIndhabitatraro() {
		return (Byte) getValue(10);
	}

	/**
	 * Setter for <code>cita.indCriaHabitatRaro</code>. Indica si la cita es de una especie criando en un habitat raro (1) o no (0)
	 */
	public void setIndcriahabitatraro(Byte value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>cita.indCriaHabitatRaro</code>. Indica si la cita es de una especie criando en un habitat raro (1) o no (0)
	 */
	public Byte getIndcriahabitatraro() {
		return (Byte) getValue(11);
	}

	/**
	 * Setter for <code>cita.indHerido</code>. Indica si el individuo/s citado/s estaba/n herido/s (1) o no (0)
	 */
	public void setIndherido(Byte value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>cita.indHerido</code>. Indica si el individuo/s citado/s estaba/n herido/s (1) o no (0)
	 */
	public Byte getIndherido() {
		return (Byte) getValue(12);
	}

	/**
	 * Setter for <code>cita.indComportamiento</code>. Descripción del comportamiento de la especie
	 */
	public void setIndcomportamiento(Byte value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>cita.indComportamiento</code>. Descripción del comportamiento de la especie
	 */
	public Byte getIndcomportamiento() {
		return (Byte) getValue(13);
	}

	/**
	 * Setter for <code>cita.especie_id</code>. Identificador de la especie
	 */
	public void setEspecieId(Integer value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>cita.especie_id</code>. Identificador de la especie
	 */
	public Integer getEspecieId() {
		return (Integer) getValue(14);
	}

	/**
	 * Setter for <code>cita.criterio_seleccion_cita_id</code>. Criterio utilizado en la selección de la cita
	 */
	public void setCriterioSeleccionCitaId(Integer value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>cita.criterio_seleccion_cita_id</code>. Criterio utilizado en la selección de la cita
	 */
	public Integer getCriterioSeleccionCitaId() {
		return (Integer) getValue(15);
	}

	/**
	 * Setter for <code>cita.indActivo</code>.
	 */
	public void setIndactivo(Byte value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>cita.indActivo</code>.
	 */
	public Byte getIndactivo() {
		return (Byte) getValue(16);
	}

	/**
	 * Setter for <code>cita.importancia_cita_id</code>. Identificador de la importancia de la cita
	 */
	public void setImportanciaCitaId(Integer value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>cita.importancia_cita_id</code>. Identificador de la importancia de la cita
	 */
	public Integer getImportanciaCitaId() {
		return (Integer) getValue(17);
	}

	/**
	 * Setter for <code>cita.estudio_id</code>.
	 */
	public void setEstudioId(Integer value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>cita.estudio_id</code>.
	 */
	public Integer getEstudioId() {
		return (Integer) getValue(18);
	}

	/**
	 * Setter for <code>cita.indPrivacidad</code>. Indica si los datos sensibles de la cita de la especie deben ser privados (0) o públicos (1)
	 */
	public void setIndprivacidad(Byte value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>cita.indPrivacidad</code>. Indica si los datos sensibles de la cita de la especie deben ser privados (0) o públicos (1)
	 */
	public Byte getIndprivacidad() {
		return (Byte) getValue(19);
	}

	/**
	 * Setter for <code>cita.indFoto</code>.
	 */
	public void setIndfoto(Byte value) {
		setValue(20, value);
	}

	/**
	 * Getter for <code>cita.indFoto</code>.
	 */
	public Byte getIndfoto() {
		return (Byte) getValue(20);
	}

	/**
	 * Setter for <code>cita.fechaCreacion</code>.
	 */
	public void setFechacreacion(Timestamp value) {
		setValue(21, value);
	}

	/**
	 * Getter for <code>cita.fechaCreacion</code>.
	 */
	public Timestamp getFechacreacion() {
		return (Timestamp) getValue(21);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record22 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row22<Integer, Timestamp, Integer, String, Byte, Integer, Integer, Integer, Integer, Integer, Byte, Byte, Byte, Byte, Integer, Integer, Byte, Integer, Integer, Byte, Byte, Timestamp> fieldsRow() {
		return (Row22) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row22<Integer, Timestamp, Integer, String, Byte, Integer, Integer, Integer, Integer, Integer, Byte, Byte, Byte, Byte, Integer, Integer, Byte, Integer, Integer, Byte, Byte, Timestamp> valuesRow() {
		return (Row22) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Cita.CITA.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field2() {
		return Cita.CITA.FECHAALTA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Cita.CITA.CANTIDAD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Cita.CITA.OBSERVACIONES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field5() {
		return Cita.CITA.INDSELECCIONADA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return Cita.CITA.LUGAR_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field7() {
		return Cita.CITA.INDRAREZAHOMOLOGADA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return Cita.CITA.OBSERVADOR_PRINCIPAL_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field9() {
		return Cita.CITA.CLASE_REPRODUCCION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field10() {
		return Cita.CITA.FUENTE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field11() {
		return Cita.CITA.INDHABITATRARO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field12() {
		return Cita.CITA.INDCRIAHABITATRARO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field13() {
		return Cita.CITA.INDHERIDO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field14() {
		return Cita.CITA.INDCOMPORTAMIENTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field15() {
		return Cita.CITA.ESPECIE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field16() {
		return Cita.CITA.CRITERIO_SELECCION_CITA_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field17() {
		return Cita.CITA.INDACTIVO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field18() {
		return Cita.CITA.IMPORTANCIA_CITA_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field19() {
		return Cita.CITA.ESTUDIO_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field20() {
		return Cita.CITA.INDPRIVACIDAD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field21() {
		return Cita.CITA.INDFOTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field22() {
		return Cita.CITA.FECHACREACION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value2() {
		return getFechaalta();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getCantidad();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getObservaciones();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value5() {
		return getIndseleccionada();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getLugarId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value7() {
		return getIndrarezahomologada();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getObservadorPrincipalId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value9() {
		return getClaseReproduccionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value10() {
		return getFuenteId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value11() {
		return getIndhabitatraro();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value12() {
		return getIndcriahabitatraro();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value13() {
		return getIndherido();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value14() {
		return getIndcomportamiento();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value15() {
		return getEspecieId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value16() {
		return getCriterioSeleccionCitaId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value17() {
		return getIndactivo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value18() {
		return getImportanciaCitaId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value19() {
		return getEstudioId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value20() {
		return getIndprivacidad();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value21() {
		return getIndfoto();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value22() {
		return getFechacreacion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CitaRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CitaRecord value2(Timestamp value) {
		setFechaalta(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CitaRecord value3(Integer value) {
		setCantidad(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CitaRecord value4(String value) {
		setObservaciones(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CitaRecord value5(Byte value) {
		setIndseleccionada(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CitaRecord value6(Integer value) {
		setLugarId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CitaRecord value7(Integer value) {
		setIndrarezahomologada(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CitaRecord value8(Integer value) {
		setObservadorPrincipalId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CitaRecord value9(Integer value) {
		setClaseReproduccionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CitaRecord value10(Integer value) {
		setFuenteId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CitaRecord value11(Byte value) {
		setIndhabitatraro(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CitaRecord value12(Byte value) {
		setIndcriahabitatraro(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CitaRecord value13(Byte value) {
		setIndherido(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CitaRecord value14(Byte value) {
		setIndcomportamiento(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CitaRecord value15(Integer value) {
		setEspecieId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CitaRecord value16(Integer value) {
		setCriterioSeleccionCitaId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CitaRecord value17(Byte value) {
		setIndactivo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CitaRecord value18(Integer value) {
		setImportanciaCitaId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CitaRecord value19(Integer value) {
		setEstudioId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CitaRecord value20(Byte value) {
		setIndprivacidad(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CitaRecord value21(Byte value) {
		setIndfoto(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CitaRecord value22(Timestamp value) {
		setFechacreacion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CitaRecord values(Integer value1, Timestamp value2, Integer value3, String value4, Byte value5, Integer value6, Integer value7, Integer value8, Integer value9, Integer value10, Byte value11, Byte value12, Byte value13, Byte value14, Integer value15, Integer value16, Byte value17, Integer value18, Integer value19, Byte value20, Byte value21, Timestamp value22) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CitaRecord
	 */
	public CitaRecord() {
		super(Cita.CITA);
	}

	/**
	 * Create a detached, initialised CitaRecord
	 */
	public CitaRecord(Integer id, Timestamp fechaalta, Integer cantidad, String observaciones, Byte indseleccionada, Integer lugarId, Integer indrarezahomologada, Integer observadorPrincipalId, Integer claseReproduccionId, Integer fuenteId, Byte indhabitatraro, Byte indcriahabitatraro, Byte indherido, Byte indcomportamiento, Integer especieId, Integer criterioSeleccionCitaId, Byte indactivo, Integer importanciaCitaId, Integer estudioId, Byte indprivacidad, Byte indfoto, Timestamp fechacreacion) {
		super(Cita.CITA);

		setValue(0, id);
		setValue(1, fechaalta);
		setValue(2, cantidad);
		setValue(3, observaciones);
		setValue(4, indseleccionada);
		setValue(5, lugarId);
		setValue(6, indrarezahomologada);
		setValue(7, observadorPrincipalId);
		setValue(8, claseReproduccionId);
		setValue(9, fuenteId);
		setValue(10, indhabitatraro);
		setValue(11, indcriahabitatraro);
		setValue(12, indherido);
		setValue(13, indcomportamiento);
		setValue(14, especieId);
		setValue(15, criterioSeleccionCitaId);
		setValue(16, indactivo);
		setValue(17, importanciaCitaId);
		setValue(18, estudioId);
		setValue(19, indprivacidad);
		setValue(20, indfoto);
		setValue(21, fechacreacion);
	}
}
